### ISSUE TITLE
Reorganize so that repo format is consistent with others

### ISSUE THREAD

**Issue by tobyMickelson** [koibots8230/RumbleBot2024#6]
Would it be possible to reorganize the structure of the repo so that it follow the same structure as our other repos with the root of the repo being the root of the project?

**Comment by eskiles** [comment]
Good catch! You'll see that as a standard for other team repos too.
Moving files around in a repo is not friendly for code merges. If you do this, be sure to

- Check in ALL feature branches.
- Merge ALL feature branches to Dev.
- Merge Dev to Main.
- Feature branch on Dev to do the move.
- Merge to Dev. Verify it is OK.
- Merge Dev to Main.
